[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin_login.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
